version: 2

models:
  - name: dim_clients
    description: "Dimension table for facilities and their reservation systems."
    columns:
      - name: client_code
        tests:
          - unique
          - not_null
      - name: reservation_system_code
        description: "Source system code: 'courtreserve' or 'podplay'"
        tests:
          - not_null

  - name: fct_reservations
    description: "Fact table of individual reservations across all facilities."
    columns:
      - name: reservation_pk
        tests:
          - unique
          - not_null
      - name: client_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_clients')
                field: client_code

  - name: dim_members
    description: "Dimension table for members across all facilities with all columns from members_raw plus reservation system code."
    columns:
      - name: member_pk
        tests:
          - unique
          - not_null
      - name: client_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_clients')
                field: client_code
      - name: external_member_id
        tests:
          - not_null
      - name: reservation_system_code
        description: "Source system code: 'courtreserve' or 'podplay'"
        tests:
          - not_null

  - name: fct_events
    description: "Fact table of events across all facilities with standardized event types."
    columns:
      - name: event_pk
        description: "Hash-based deterministic identifier for deduplicating events"
        tests:
          - unique
          - not_null
      - name: client_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_clients')
                field: client_code
      - name: source_system
        tests:
          - not_null
      - name: event_id
        tests:
          - not_null
      - name: event_type_original
        description: "Original event type from the raw table before mapping"
      - name: event_type
        description: "Standardized event type (Class, Open Play, Compete, or original value)"
      - name: event_start_time
        tests:
          - not_null

  - name: fct_court_availability
    description: "Fact table of available court time slots across all facilities (CourtReserve and Podplay)."
    columns:
      - name: availability_pk
        description: "Surrogate key for availability records"
        tests:
          - unique
          - not_null
      - name: client_code
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_clients')
                field: client_code
      - name: source_system
        description: "Source system: 'courtreserve' or 'podplay'"
        tests:
          - not_null
      - name: court_id
        tests:
          - not_null
      - name: court_name
        tests:
          - not_null
      - name: slot_start
        description: "Start time of available slot (UTC)"
        tests:
          - not_null
      - name: slot_end
        description: "End time of available slot (UTC)"
        tests:
          - not_null
      - name: duration_minutes
        description: "Duration of slot in minutes"
