-- Idempotent seed data for courtlink-elt
-- This file can be run multiple times without causing errors
-- Uses :schema placeholder which will be replaced with PG_SCHEMA env var

-- ============================================================================
-- ORGANIZATIONS
-- ============================================================================

INSERT INTO :schema.organizations (
    id,
    source_system_code,
    client_code,
    login_link,
    city,
    is_customer,
    hourly_rate_non_member,
    hourly_rate_member,
    hourly_rate_non_member_off_peak,
    hourly_rate_member_off_peak,
    facility_display_name,
    peak_hours,
    location_display_name,
    podplay_pod,
    podplay_pod_id,
    operating_hours,
    google_place_id,
    google_photo_name
) VALUES 
    (
        1,
        'courtreserve',
        'pklyn',
        'https://app.courtreserve.com/Online/Account/LogIn/11868',
        NULL,
        true,
        110,
        90,
        90,
        88,
        'PKLYN',
        '{"weekday_peak": null, "weekend_peak": null, "weekday_off_peak": null}'::jsonb,
        'Gowanus',
        NULL,
        NULL,
        '{"timezone": "America/New_York", "monday": {"open": "07:00", "close": "23:00"}, "tuesday": {"open": "07:00", "close": "23:00"}, "wednesday": {"open": "07:00", "close": "23:00"}, "thursday": {"open": "07:00", "close": "23:00"}, "friday": {"open": "07:00", "close": "23:00"}, "saturday": {"open": "07:00", "close": "23:00"}, "sunday": {"open": "07:00", "close": "23:00"}}'::jsonb,
        'ChIJ6Vqd9DRbwokRSADznFwsZjE',
        NULL
    ),
    (
        2,
        'podplay',
        'redhookpickleball',
        'https://redhookpickleball.podplay.app/login?redirect=%2Fapp-menus&loginMode=password',
        'brooklyn',
        false,
        99,
        75,
        79,
        60,
        'Red Hook Pickleball Club',
        '{"timezone": "America/New_York", "weekday_peak": [{"end": "10:00", "start": "07:00"}, {"end": "22:00", "start": "17:00"}], "weekend_peak": null, "weekday_off_peak": [{"end": "17:00", "start": "10:00"}]}'::jsonb,
        'Red Hook',
        NULL,
        NULL,
        NULL,
        'ChIJu9n_3qdbwokRTSWmmv-IDGA',
        NULL
    ),
    (
        3,
        'podplay',
        'goodland',
        'https://goodland.podplay.app/login?redirect=%2Fapp-menus&loginMode=password',
        'greenpoint-indoor',
        false,
        110,
        66,
        80,
        48,
        'Goodland Pickleball',
        '{"weekday_peak": null, "weekend_peak": null, "weekday_off_peak": null}'::jsonb,
        'Greenpoint',
        'greenpoint-indoor-1',
        NULL,
        NULL,
        'ChIJ8aFJDkdZwokRTNVl61aDHEk',
        NULL
    ),
    (
        4,
        'podplay',
        'gotham',
        'https://gotham.podplay.app/login?redirect=%2Fapp-menus&loginMode=password',
        'long-island-city',
        true,
        110,
        88,
        80,
        60,
        'Gotham Picklball',
        '{"timezone": "America/New_York", "weekday_peak": [{"end": "10:00", "start": "07:00"}, {"end": "22:00", "start": "17:00"}], "weekend_peak": null, "weekday_off_peak": [{"end": "17:00", "start": "10:00"}]}'::jsonb,
        'Long Island City',
        NULL,
        'e6e67f0a-de3f-4e6e-adf5-3db126cd5c83',
        '{"timezone": "America/New_York", "monday": {"open": "05:00", "close": "01:00"}, "tuesday": {"open": "05:00", "close": "01:00"}, "wednesday": {"open": "05:00", "close": "01:00"}, "thursday": {"open": "05:00", "close": "01:00"}, "friday": {"open": "05:00", "close": "01:00"}, "saturday": {"open": "05:00", "close": "01:00"}, "sunday": {"open": "05:00", "close": "01:00"}}'::jsonb,
        'ChIJz5aALZVZwokRh6INsy29MsA',
        NULL
    ),
    (
        5,
        'podplay',
        'citypickle',
        'https://citypickle.podplay.app/login?redirect=%2Fapp-menus&loginMode=password',
        'long-island',
        false,
        99,
        79,
        50,
        40,
        'CityPickle',
        '{"timezone": "America/New_York", "weekday_peak": [{"end": "10:00", "start": "07:00"}, {"end": "22:00", "start": "17:00"}], "weekend_peak": null, "weekday_off_peak": null}'::jsonb,
        'Long Island City',
        'long-island-open',
        NULL,
        NULL,
        'ChIJu4iGZCVZwokRcsvTXbYxYuA',
        NULL
    ),
    (
        6,
        'podplay',
        'velto',
        'https://velto.podplay.app/login?redirect=%2Fapp-menus&loginMode=password',
        'red-hook',
        false,
        99,
        79,
        99,
        59,
        'Velto Pickleball',
        '{"timezone": "America/New_York", "weekday_peak": [{"end": "22:00", "start": "17:00"}], "weekend_peak": [{"end": "22:00", "start": "08:00"}], "weekday_off_peak": [{"end": "17:00", "start": "08:00"}]}'::jsonb,
        'Red Hook',
        NULL,
        NULL,
        NULL,
        'ChIJey0moGBawokRzVfVRnTGb8A',
        NULL
    )
ON CONFLICT (id) DO UPDATE SET
    source_system_code = EXCLUDED.source_system_code,
    client_code = EXCLUDED.client_code,
    login_link = EXCLUDED.login_link,
    city = EXCLUDED.city,
    is_customer = EXCLUDED.is_customer,
    hourly_rate_non_member = EXCLUDED.hourly_rate_non_member,
    hourly_rate_member = EXCLUDED.hourly_rate_member,
    hourly_rate_non_member_off_peak = EXCLUDED.hourly_rate_non_member_off_peak,
    hourly_rate_member_off_peak = EXCLUDED.hourly_rate_member_off_peak,
    facility_display_name = EXCLUDED.facility_display_name,
    peak_hours = EXCLUDED.peak_hours,
    location_display_name = EXCLUDED.location_display_name,
    podplay_pod = EXCLUDED.podplay_pod,
    podplay_pod_id = EXCLUDED.podplay_pod_id,
    operating_hours = EXCLUDED.operating_hours,
    google_place_id = EXCLUDED.google_place_id,
    google_photo_name = EXCLUDED.google_photo_name;


-- ============================================================================
-- COURTS
-- ============================================================================

INSERT INTO :schema.courts (
    id,
    client_code,
    label,
    type_name,
    order_index,
    created_at,
    updated_at
) VALUES 
    (44076, 'pklyn', 'Court #1', 'Pickleball', 1, '2025-11-17 11:33:38.829405-05', '2025-11-17 11:33:38.829405-05'),
    (44077, 'pklyn', 'Court #2', 'Pickleball', 2, '2025-11-17 11:33:38.829405-05', '2025-11-17 11:33:38.829405-05'),
    (44078, 'pklyn', 'Court #3', 'Pickleball', 3, '2025-11-17 11:33:38.829405-05', '2025-11-17 11:33:38.829405-05'),
    (44079, 'pklyn', 'Court #4', 'Pickleball', 4, '2025-11-17 11:33:38.829405-05', '2025-11-17 11:33:38.829405-05'),
    (44080, 'pklyn', 'Court #5', 'Pickleball', 5, '2025-11-17 11:33:38.829405-05', '2025-11-17 11:33:38.829405-05')
ON CONFLICT (id) DO UPDATE SET
    client_code = EXCLUDED.client_code,
    label = EXCLUDED.label,
    type_name = EXCLUDED.type_name,
    order_index = EXCLUDED.order_index,
    updated_at = EXCLUDED.updated_at;

-- ============================================================================
-- FACILITY DETAILS
-- ============================================================================

INSERT INTO :schema.facility_details (
    client_code,
    street_address,
    city,
    state,
    zip_code,
    country,
    latitude,
    longitude,
    full_address,
    number_of_courts,
    primary_court_type,
    court_types,
    indoor_outdoor,
    court_surface_type,
    has_showers,
    has_lounge_area,
    has_paddle_rentals,
    has_pro_shop,
    has_food_service,
    has_parking,
    parking_type,
    has_wifi,
    has_lockers,
    has_water_fountains,
    has_dink_court,
    has_workout_area,
    is_autonomous_facility,
    facility_type,
    year_opened,
    facility_size_sqft,
    amenities_list,
    notes,
    facility_metadata
) VALUES 
    (
        'pklyn',
        '80 4th St',
        'Brooklyn',
        'NY',
        '11231',
        'USA',
        40.67672573500147,
        -73.993297626984,
        '80 4th St, Brooklyn, NY 11231, USA',
        5,
        NULL,
        NULL,
        'indoor',
        NULL,
        true,
        true,
        true,
        true,
        true,
        false,
        NULL,
        true,
        true,
        true,
        true,
        true,
        false,
        'private',
        2024,
        18000,
        NULL,
        NULL,
        NULL
    ),
    (
        'gotham',
        '5-25 46th Ave',
        'Long Island City',
        'NY',
        '11101',
        'USA',
        40.74761843321619,
        -73.9542153194257,
        '5-25 46th Ave, Long Island City, NY 11101, USA',
        4,
        NULL,
        NULL,
        'indoor',
        NULL,
        false,
        false,
        false,
        false,
        false,
        false,
        NULL,
        true,
        false,
        true,
        false,
        false,
        true,
        'private',
        2024,
        7800,
        'free_paddles_borrow',
        NULL,
        NULL
    ),
    (
        'redhookpickleball',
        '262 Van Brunt St',
        'Brooklyn',
        'NY',
        '11231',
        'USA',
        40.68070423296283,
        -74.0097362175778,
        '262 Van Brunt St, Brooklyn, NY 11231, USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        'goodland',
        '67 West St Suite 110',
        'Brooklyn',
        'NY',
        '11222',
        'USA',
        40.728958221910496,
        -73.95995640408287,
        '67 West St Suite 110, Brooklyn, NY 11222, USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        'citypickle',
        '9-03 44th Rd',
        'Long Island City',
        'NY',
        '11101',
        'USA',
        40.75037973285398,
        -73.95089150000004,
        '9-03 44th Rd, Long Island City, NY 11101, USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        'velto',
        '160 Van Brunt St',
        'Brooklyn',
        'NY',
        '11231',
        'USA',
        40.700023165963024,
        -74.00285361760457,
        '160 Van Brunt St, Brooklyn, NY 11231, USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    )
ON CONFLICT (client_code) DO UPDATE SET
    street_address = EXCLUDED.street_address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip_code = EXCLUDED.zip_code,
    country = EXCLUDED.country,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    full_address = EXCLUDED.full_address,
    number_of_courts = EXCLUDED.number_of_courts,
    primary_court_type = EXCLUDED.primary_court_type,
    court_types = EXCLUDED.court_types,
    indoor_outdoor = EXCLUDED.indoor_outdoor,
    court_surface_type = EXCLUDED.court_surface_type,
    has_showers = EXCLUDED.has_showers,
    has_lounge_area = EXCLUDED.has_lounge_area,
    has_paddle_rentals = EXCLUDED.has_paddle_rentals,
    has_pro_shop = EXCLUDED.has_pro_shop,
    has_food_service = EXCLUDED.has_food_service,
    has_parking = EXCLUDED.has_parking,
    parking_type = EXCLUDED.parking_type,
    has_wifi = EXCLUDED.has_wifi,
    has_lockers = EXCLUDED.has_lockers,
    has_water_fountains = EXCLUDED.has_water_fountains,
    has_dink_court = EXCLUDED.has_dink_court,
    has_workout_area = EXCLUDED.has_workout_area,
    is_autonomous_facility = EXCLUDED.is_autonomous_facility,
    facility_type = EXCLUDED.facility_type,
    year_opened = EXCLUDED.year_opened,
    facility_size_sqft = EXCLUDED.facility_size_sqft,
    amenities_list = EXCLUDED.amenities_list,
    notes = EXCLUDED.notes,
    facility_metadata = EXCLUDED.facility_metadata,
    updated_at = EXCLUDED.updated_at;

-- ============================================================================
-- SUMMARY
-- ============================================================================
-- Organizations: 6 rows (1 CourtReserve, 5 Podplay)
-- Courts: 5 rows (all PKLYN)
-- Facility Details: 6 rows (pklyn, gotham, redhookpickleball, goodland, citypickle, velto)
--
-- Operating Hours (stored in local time with timezone):
--   - PKLYN: 7am-11pm (America/New_York timezone)
--   - Gotham: 5am-1am (America/New_York timezone)
--
-- Peak Hours (stored in local time with timezone):
--   - Peak: 7am-10am and 5pm-10pm (America/New_York timezone)
--   - Off-Peak: 10am-5pm (America/New_York timezone)
--
-- Note: Times are stored in local facility timezone (America/New_York) with timezone metadata.
-- This automatically handles DST transitions - no need to update seed file twice a year.
-- The ingestion and dbt models convert to UTC when needed for comparisons.
-- When close time is less than open time, it crosses to the next day.
-- ============================================================================

